#cloud-config
# Cloud-init configuration for Linode VPS

# Basic system configuration
hostname: docker-mon-tshark
package_update: true
package_upgrade: true
package_reboot_if_required: true
timezone: "UTC"
locale: "en_US.UTF-8"

# Security-focused user configuration
users:
  - name: deploy
    groups: [sudo, docker]
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ${ssh_public_key}

# Essential packages for security and functionality
packages:
  - curl
  - wget
  - fail2ban
  - ufw
  - unattended-upgrades
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release

# Security hardening files
write_files:
  - path: /etc/ssh/sshd_config.d/99-hardening.conf
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      PubkeyAuthentication yes
      MaxAuthTries 3
      LoginGraceTime 30
      ClientAliveInterval 300
      ClientAliveCountMax 2
    owner: root:root
    permissions: '0644'
  
  - path: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      bantime = 3600
      findtime = 600
      maxretry = 3
      
      [sshd]
      enabled = true
      port = ssh
      filter = sshd
      logpath = /var/log/auth.log
    owner: root:root
    permissions: '0644'

# Configure automatic security updates
  - path: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
      APT::Periodic::AutocleanInterval "7";
    owner: root:root
    permissions: '0644'

# System configuration commands
runcmd:
  # Configure UFW firewall
  - ufw --force reset
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow ssh
  - ufw --force enable
  
  # Install Tailscale
  - curl -fsSL https://tailscale.com/install.sh | sh
  - tailscale up --auth-key=${tailscale_auth_key} --accept-routes --ssh
  
  # Install Docker with security verification
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - apt-get upgrade -y
  - apt-get dist-upgrade -y
  
  # Secure Docker daemon configuration
  - mkdir -p /etc/docker
  - |
    cat > /etc/docker/daemon.json << EOF
    {
      "live-restore": true,
      "userland-proxy": false,
      "no-new-privileges": true,
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "10m",
        "max-file": "3"
      }
    }
    EOF
  
  # Start and enable services
  - systemctl enable docker
  - systemctl start docker
  - systemctl enable fail2ban
  - systemctl start fail2ban
  - systemctl restart sshd
  
  # Add deploy user to docker group (optional, for convenience)
  - usermod -aG docker deploy
  
  # Final security lockdown
  - chmod 700 /home/deploy/.ssh
  - chown -R deploy:deploy /home/deploy/.ssh

# Reboot after initial setup
power_state:
  mode: reboot
  condition: True